colors:
  blue: "\033[94m"
  cyan: "\033[96m"
  green: "\033[92m"
  red: "\033[91m"
  reset: "\033[0m"
  yellow: "\033[93m"
dataset:
  name: hotpotqa/hotpot_qa
  num_samples: 10
  split: validation
epsilon: 3.0
local_model: meta-llama/Meta-Llama-3.1-8B-Instruct
local_models:
- microsoft/phi-4
- google/gemma-2-9b-it-fast
- google/gemma-2-2b-it
- Qwen/Qwen2.5-Coder-7B
- mistralai/Mistral-Nemo-Instruct-2407
- meta-llama/Meta-Llama-3.1-8B-Instruct
- Qwen/Qwen3-4B-fast
- Qwen/Qwen3-14B
max_tokens: 256
num_return_sequences: 10
original_dataset:
  name: GBaker/MedQA-USMLE-4-options
  num_samples: 200
  split: test
remote_llm_provider: deepseek
remote_models:
  cot_model: deepseek-v3
  judge_model: deepseek-v3
  llm_model: deepseek-v3
temperature: 0.0
